// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEDbPZZh5n2fgGtGKBQUuqyWufkQKf5hQ',
    appId: '1:707709987531:web:172fa074058e14356c094e',
    messagingSenderId: '707709987531',
    projectId: 'cybersafe-f366a',
    authDomain: 'cybersafe-f366a.firebaseapp.com',
    storageBucket: 'cybersafe-f366a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD-mXHpCXlqbHHsHpGJq4TrIlEK_8c2lc',
    appId: '1:707709987531:android:f9c84e0a29d5233f6c094e',
    messagingSenderId: '707709987531',
    projectId: 'cybersafe-f366a',
    storageBucket: 'cybersafe-f366a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtfL5dFV1xOXXfik2yBumANdt9KmvgL5o',
    appId: '1:707709987531:ios:757b35be986599f76c094e',
    messagingSenderId: '707709987531',
    projectId: 'cybersafe-f366a',
    storageBucket: 'cybersafe-f366a.firebasestorage.app',
    iosBundleId: 'com.example.mobilePsh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtfL5dFV1xOXXfik2yBumANdt9KmvgL5o',
    appId: '1:707709987531:ios:757b35be986599f76c094e',
    messagingSenderId: '707709987531',
    projectId: 'cybersafe-f366a',
    storageBucket: 'cybersafe-f366a.firebasestorage.app',
    iosBundleId: 'com.example.mobilePsh',
  );
}
